### PR TITLE
chore: build only one python version per github action matrix entry

### LINKED ISSUE #63: De-dupe test runs for manylinux
Currently, test runs are matrixed in the github action, as well as centos build. https://github.com/googleapis/python-crc32c/blob/master/scripts/manylinux/build_on_centos.sh against python 3.6...3.10

One or the other can be simplified so we aren't rebuilding/retesting configurations.

### LINKED ISSUE #70: CI appears to be broken
I am trying to make sure we have renovate enabled in all the places we should.  I re-opened the PR here:
https://github.com/googleapis/python-crc32c/pull/8

It looks like a bunch of tests unrelated to my change are failing.  We should fix that!

### PR DESCRIPTION
**Pull request by tseaver**
Closes #63.

Closes #70.

### CODE REVIEW

**Review by JustinBeckwith — APPROVED** [review]
Thank you :)

**Comment by tseaver** [comment]
@JustinBeckwith I might have spoken too soon -- the environment variable I'm setting in the Github Action doesn't seem to be propagated to the `scripts/manylinux/build_on_centos.sh` script.

**Comment by tseaver** [comment]
FTR, the thing which eluded me was the need to push the `BUILD_PYTHON` bit down explicitly into the docker commands in `scripts/manylinux/bulid.sh`.

**Comment by tseaver** [comment]
@JustinBeckwith Heh, your approval-fu is too weak for this repo. ;)

**Review by dandhlee — APPROVED** [review]
LGTM.

**Pull request merged**
