### PR TITLE
change package name in setup.py

### PR DESCRIPTION
**Pull request by crwilcox**

### CODE REVIEW

**Comment by dhermes** [comment]
You need to change it it many more places. I suggest `git grep python-crc32c` and `git grep python_crc32c`.

**Comment by dhermes** [comment]
LGTM, though the wheels shouldn't be renamed, they need to be rebuilt. Also, the macOS wheels are for the OLD source (note the `py_crc32*` prefix vs. the `python_crc32*`), so they **really** shouldn't be renamed.

**Comment by dhermes** [comment]
Feel free to just remove `wheels/` entirely from the product. Make a public GCS bucket and put newly built wheels there?

**Comment by jlaine** [comment]
This was a good change, the naming was highly confusing previously.

In the interest of consistency, could this repo also be renamed to `google-crc32c`?

**Pull request merged**
